server:
  port: 2999

spring:
  application:
    name: jpa-test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33306/jpatest?serverTimezone=UTC
    username: test-user
    password: 1q2w3e4r@@
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: true
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
  data:
    redis:
      host: localhost
      port: 6399

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.orm: TRACE
    org.springframework.transaction: TRACE
